INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT ) VALUES ( 1, '게시글_작성자_01', '게시글_제목_01', '게시글_내용_01' );

INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT ) VALUES ( 2, '게시글_작성자_02', '게시글_제목_02', '게시글_내용_02' );

INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT ) VALUES ( 3, '게시글_작성자_03', '게시글_제목_03', '게시글_내용_03' );



INSERT INTO TBL_USER ( USER_SEQ, USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL ) VALUES ( 1, 'TEST_01', 'PASSWORD', 'TESTER_01', 'TEST_01@NAVER.COM' );

INSERT INTO TBL_USER ( USER_SEQ, USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL ) VALUES ( 2, 'TEST_02', 'PASSWORD', 'TESTER_02', 'TEST_03@NAVER.COM' );

INSERT INTO TBL_USER ( USER_SEQ, USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL ) VALUES ( 3, 'TEST_03', 'PASSWORD', 'TESTER_03', 'TEST_03@NAVER.COM' );


