INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT ) VALUES ( 1, '게시글_작성자_01', '게시글_제목_01', '게시글_내용_01' );

INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT ) VALUES ( 2, '게시글_작성자_02', '게시글_제목_02', '게시글_내용_02' );

INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT ) VALUES ( 3, '게시글_작성자_03', '게시글_제목_03', '게시글_내용_03' );